services:
  www:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb:lts-noble
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: jesusdb
      MYSQL_USER: jesus
      MYSQL_PASSWORD: 2025
      MYSQL_ROOT_PASSWORD: 2025
    volumes:
      - ./base_datos:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: jesus
      MYSQL_PASSWORD: 2025
      MYSQL_ROOT_PASSWORD: 2025